name: Get Pulumi Secret Output

description: Put a pulumi secret output into the environment
inputs:
  stack-name:
    description: The pulumi stack
    required: true
  infra-path:
      description: The path to the pulumi infra project
      required: false
      default: ./infra/
  pulumi-key:
      description: The Pulumi key
      required: true
  environment-variable:
      description: The Environment variable
      required: true      

runs:
  using: composite
  steps:
    - name: Retrieve ${{ inputs.pulumi-key }} secret into ${{ inputs.environment-variable }}
      run: |  
            while read -r line;
            do
              echo "::add-mask::${line}"
            done <<< $(/usr/local/bin/pulumi stack output ${{ inputs.pulumi-key }} -s ${{ inputs.stack-name }} -C ${{ inputs.infra-path}} --non-interactive --show-secrets)
            
            EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
            echo "${{ inputs.environment-variable }}<<$EOF" >> $GITHUB_ENV
            /usr/local/bin/pulumi stack output ${{ inputs.pulumi-key }} -s ${{ inputs.stack-name }} -C ${{ inputs.infra-path}}  --non-interactive --show-secrets >> $GITHUB_ENV
            echo "$EOF" >> $GITHUB_ENV
      shell: bash
#            echo "${{ inputs.environment-variable }}=$(/usr/local/bin/pulumi stack output ${{ inputs.pulumi-key }} -s ${{ inputs.stack-name }} -C ${{ inputs.infra-path}}  --non-interactive --show-secrets)" >> $GITHUB_ENV

#             echo  "::add-mask::$(/usr/local/bin/pulumi stack output ${{ inputs.pulumi-key }} -s ${{ inputs.stack-name }} -C ${{ inputs.infra-path}} --non-interactive --show-secrets)"
